config/routes.rb
Rails.application.routes.draw do

  root to: 'main#index'

  get 'client' => 'matches#index'

  get 'mmr_boost' => 'main#mmr_boost'

  get 'preparation' => 'main#preparation'

  get 'checkout' => 'main#checkout'

  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :matches, only: [:index, :show]

  resources :boost_mmr do
    get 'create'
    post 'update', on: :collection

  end

  resources :conversations do
    resources :messages
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def mmr_boost
    @heroes = Hero.all

    arr_of_str = ["Abaddon", "Alchemist", "Axe", "Beastmaster", "Brewmaster", "Bristleback", "Centaur Warrunner", "Chaos Knight", "Clockwerk", "Doom", "Dragon Knight", "Earth Spirit", "Earthshaker", "Elder Titan", "Huskar", "Io", "Kunkka", "Legion Commander", "Lifestealer", "Lycan", "Magnus", "Night Stalker", "Omniknight", "Phoenix", "Pudge", "Sand King", "Slardar", "Spirit Breaker", "Sven", "Tidehunter", "Timbersaw", "Tiny", "Treant Protector", "Tusk", "Underlord", "Undying", "Wraith King"]
    arr_of_agi = ["Anti-Mage", "Arc Warden", "Bloodseeker", "Bounty Hunter", "Broodmother", "Clinkz", "Drow Ranger", "Ember Spirit", "Faceless Void", "Gyrocopter", "Juggernaut", "Lone Druid", "Luna", "Medusa", "Meepo", "Mirana", "Monkey King", "Morphling", "Naga Siren", "Nyx Assassin", "Pangolier", "Phantom Assassin", "Phantom Lancer", "Razor", "Riki", "Shadow Fiend", "Slark", "Sniper", "Spectre", "Templar Assassin", "Terrorblade", "Troll Warlord", "Ursa", "Vengeful Spirit", "Venomancer", "Viper", "Weaver"]
    arr_of_int = ["Ancient Apparition", "Bane", "Batrider", "Chen", "Crystal Maiden", "Dark Seer", "Dark Willow", "Dazzle", "Death Prophet", "Disruptor", "Enchantress", "Enigma", "Invoker", "Jakiro", "Keeper of the Light", "Leshrac", "Lich", "Lina", "Lion", "Nature's Prophet", "Necrophos", "Ogre Magi", "Oracle", "Outworld Devourer", "Puck", "Pugna", "Queen of Pain", "Rubick", "Shadow Demon", "Shadow Shaman", "Silencer", "Skywrath Mage", "Storm Spirit", "Techies", "Tinker", "Visage", "Warlock", "Windranger", "Winter Wyvern", "Witch Doctor", "Zeus"]
    @arr_of_str = []
    @arr_of_agi = []
    @arr_of_int = []

    @heroes.each do |str_hero|
      arr_of_str.each do |hero|
        @arr_of_str << str_hero if str_hero.localized_name == hero
      end
    end

    @heroes.each do |str_hero|
      arr_of_agi.each do |hero|
        @arr_of_agi << str_hero if str_hero.localized_name == hero
      end
    end

    @heroes.each do |str_hero|
      arr_of_int.each do |hero|
        @arr_of_int << str_hero if str_hero.localized_name == hero
      end
    end

  end

  def preparation

  end

  def checkout

  end


end

app/views/main/checkout.html.erb
<div class="container">
  <div class="col-xs-ptm-10 col-xs-11 col-md-9 xs-pl-0 lg-pl-15 white ssd"
       style="border: 1px solid #f6f6f6;; padding-top: 20px; padding-bottom: 15px">
    <%= form_for :boost, :url => url_for(:controller => 'boost_mmr', :action => 'update') do |f| %>

      <div class="col-md-4">
          <div class="form-group">
            <%= f.label :login, 'Login'%>
            <%= f.number_field :login, {id: 'login', autocomplete: "off",
                                          class: "form-control form-control-lg cnt", style: "width:180px;", required: true}%>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :password, 'Password'%>
            <%= f.number_field :password, {id: 'password', autocomplete: "off",
                                          class: "form-control form-control-lg cnt", style: "width:180px;", required: true}%>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :email, 'Email'%>
            <%= f.number_field :email, {id: 'email', autocomplete: "off",
                                          class: "form-control form-control-lg cnt", style: "width:180px;", required: true}%>
          </div>
        </div>

        <% params.except(:action, :controller).each do |name, value| %>
            <%= f.hidden_field name.to_sym, :value => value %>
        <% end %>
        <%= f.hidden_field :user_id, value: current_user.id if current_user %>

        <%= f.submit "Next step", class: "btn btn-lg orange-button btn-block", style: 'margin-top: 3px;'%>
      <% end %>
  </div>
</div>

app/views/main/preparation.html.erb
<div class="container">
  <h2>Preparation</h2>
  <%= params.except(:action, :controller) %>
  <%= link_to 'previous step', mmr_boost_path %>
  <%= link_to 'next step', checkout_path(params.except(:action, :controller)) %>
</div>