config/routes.rb
Rails.application.routes.draw do

  root to: 'main#index'

  get 'client' => 'matches#index'

  get 'mmr_boost' => 'main#mmr_boost'

  get 'preparation' => 'main#preparation'

  get 'checkout' => 'main#checkout'

  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :matches, only: [:index, :show]

  resources :boost_mmr do
    get 'create'
    post 'update', on: :collection

  end

  resources :conversations do
    resources :messages
  end

end

app/models/match.rb
=begin
require 'net/http'
=end

class Match < ActiveRecord::Base
  belongs_to :user
  has_many :players, dependent: :delete_all
  has_many :items
  after_save :load_players!

  def load_players!
    match_request =
        NetHttpService.new("https://api.steampowered.com/IDOTA2Match_570/GetMatchDetails/V001/?match_id=#{self.uid}&key=#{ENV["STEAM_KEY"]}").get_request
    match_info = JSON.parse(match_request)
=begin

    match_info = Dota.api.matches((self.uid).to_i)
    roster = {radiant: match_info.radiant, dire: match_info.dire}
    roster.each_pair do |k, v|
=end

    match_info["result"]["players"].each do |player|
      self.players.create({
                              uid: player["account_id"],
                              items: get_player_items(match_info, player["player_slot"]).map{ |item|  {
                                  id: item,
                                  name: name = item_name(item),
                                  image: "http://cdn.dota2.com/apps/dota2/images/items/#{name}_lg.png"
                              }},
                              hero: {id: player["hero_id"],
                                     name: name = hero_name(player["hero_id"]),
                                     localized_name: hero_localized_name(player["hero_id"]),
                                     image: "http://cdn.dota2.com/apps/dota2/images/heroes/#{name}_hphover.png"},
                              level: player["level"],
                              kills: player["kills"],
                              deaths: player["deaths"],
                              assists: player["assists"],
                              last_hits: player["last_hits"],
                              denies: player["denies"],
                              gold: player["gold"],
                              gpm: player["gold_per_min"],
                              xpm: player["xp_per_min"],
                              status: match_info["result"]["radiant_win"].to_s.titleize,
                              gold_spent: player["gold_spent"],
                              hero_damage: player["hero_damage"],
                              tower_damage: player["tower_damage"],
                              hero_healing: player["hero_healing"],
                              slot: player["player_slot"],
                              radiant: player["player_slot"] <= 4 ? true : false
                          })
    end
=begin
    end
=end
  end

  private

  def hero_name(id)
    Hero.find_by(dota_api_id: id).name
  end

  def hero_localized_name(id)
    Hero.find_by(dota_api_id: id).localized_name
  end

  def item_name(id)
    if id == 0
      "Empty"
    else
      Item.find_by(dota_api_id: id).name.gsub("kaya", "trident")
    end
    rescue => e
  end

  def get_player_items(match_hash, player_slot)
    player_params = match_hash["result"]["players"].find { |current| current["player_slot"] == player_slot}
    [player_params["item_0"], player_params["item_1"], player_params["item_2"],
     player_params["item_3"], player_params["item_4"], player_params["item_5"]]
  end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    current_user.load_matches!
    @matches = current_user.matches.order('started_at DESC') if current_user
    @users = User.all

  end

  def show
    @match = Match.includes(:players).find_by(id: params[:id])
    @players = @match.players.order('slot ASC').group_by(&:radiant)
  end

end

app/views/matches/_player_hero.html.erb
<%= image_tag hero[:image], alt: hero[:localized_name], title: hero[:localized_name] %>

app/views/matches/_players_table.html.erb
<table class="table table-hover table-striped info-table">
  <tr>
    <th>Player ID</th>
    <th>Hero</th>
    <th>Level</th>
    <th>Items</th>
    <th>Kills</th>
    <th>Deaths</th>
    <th>Assists</th>
    <th><abbr title="Last hits">LH</abbr></th>
    <th><abbr title="Denies">DN</abbr></th>
    <th>Gold (spent)</th>
    <th><abbr title="Gold per minute">GPM</abbr></th>
    <th><abbr title="Experience per minute">XPM</abbr></th>
    <th><abbr title="Hero damage">HD</abbr></th>
    <th><abbr title="Tower damage">TD</abbr></th>
    <th><abbr title="Hero healing">HH</abbr></th>
  </tr>
  <% players.each do |player| %>
      <tr>
        <td>
          <% if player.abandoned_or_not_connected? %>
              <abbr class="text-muted" title="<%= player.status.titleize %>"><%= player.uid %></abbr>
          <% else %>
              <%= player.uid %>
          <% end %>
        </td>
        <td><%= render 'player_hero', hero: player.hero %></td>
        <td><%= player.level %></td>
        <td>
          <% player.items.each do |item| %>
              <% if item[:name] == "Empty" %>
                  <span class="empty"> </span>
              <% else %>
                  <%= image_tag item[:image], alt: item[:name], title: item[:name] %>
              <% end %>
          <% end %>
        </td>
        <td><%= player.kills %></td>
        <td><%= player.deaths %></td>
        <td><%= player.assists %></td>
        <td><%= player.last_hits %></td>
        <td><%= player.denies %></td>
        <td><%= player.gold %> (<%= player.gold_spent %>)</td>
        <td><%= player.gpm %></td>
        <td><%= player.xpm %></td>
        <td><%= player.hero_damage %></td>
        <td><%= player.tower_damage %></td>
        <td><%= player.hero_healing %></td>
      </tr>
  <% end %>
</table>

app/views/matches/index.html.erb
<% page_header 'Your matches' %>

<script type="text/javascript">

    $(document).ready(function () {
        $('#an-id').trigger('click');
    });

</script>

<% @users.each_with_index do |user, index| %>
    <tr>
      <td><%= index +=1 %></td>
      <td><%= user.nickname %></td>
      <td>
        <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation", id: "an-id", style: "display: none",
                    "data-sid" => current_user.id, "data-rip" => user.id %>
      </td>
    </tr>
<% end %>

<hr>

<% if @matches && @matches.any? %>
    <table class="table table-striped table-hover info-table">
      <% @matches.each do |match| %>
          <tr>
            <td>
              <%= render 'player_hero', hero: current_user.played_for_in(match) %>
              <%= current_user.played_for_in(match)[:localized_name] %>
              <% current_user.player_items(match).each do |item| %>
                  <% if item[:name] == "Empty" %>
                      <span class="empty"> </span>
                  <% else %>
                      <%= image_tag item[:image], alt: item[:name], title: item[:name] %>
                  <% end %>
              <% end %>
              <%= link_to match.started_at.strftime("%d.%m.%Y %H:%M"), match_path(match) %>
              <% if current_user.won?(match) %>
                  <span class="label label-success">won</span>
              <% else %>
                  <span class="label label-danger">lost</span>
              <% end %>
            </td>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/matches/show.html.erb
<% page_header "Match #{@match.uid} <small>#{@match.started_at}</small>" %>

<h2 class="<%= @match.winner.downcase %>"><%= @match.winner %> won</h2>

<ul>
  <li><strong>Mode:</strong> <%= @match.mode %></li>
  <li><strong>Type:</strong> <%= @match.match_type %></li>
  <li><strong>Duration:</strong> <%= @match.duration %></li>
</ul>

<h3 class="radiant">Team Radiant</h3>

<%= render 'players_table', players: @players[true] %>

<h3 class="dire">Team Dire</h3>

<%= render 'players_table', players: @players[false] %>