config/routes.rb
Rails.application.routes.draw do

  root to: 'main#index'

  get 'client' => 'matches#index'

  get 'mmr_boost' => 'main#mmr_boost'

  get 'preparation' => 'main#preparation'

  get 'checkout' => 'main#checkout'

  match '/auth/:provider/callback', to: 'sessions#create', via: :all
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :matches, only: [:index, :show]

  resources :boost_mmr do
    get 'create'
    post 'update', on: :collection

  end

  resources :conversations do
    resources :messages
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Boost</title>

  <meta content='<%= current_user ? current_user.id : "" %>' name='user-id'/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

</head>
<body>

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'UPRANK', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <% if current_user %>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'MMR boost', mmr_boost_path %></li>
            <li><%= link_to 'Personal', client_path %></li>
            <li><%= image_tag current_user.avatar_url, alt: current_user.nickname %></li>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav">
            <li><%= link_to "<i class=\"fa fa-steam\" aria-hidden=\"true\"></i>".html_safe + ' Log In via Steam', '/auth/steam' %></li>
          </ul>
      <% end %>
    </div>
  </div>
</nav>

  <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
          toastr['<%= type %>']('<%= f[1] %>');
          <% end %>
      </script>
  <% end %>


  <%= yield %>

</div>

<audio id="chatAudio"><source src="/sounds/notification.mp3" type="audio/mpeg"></audio>

</body>
</html>